# Generated by Django 4.2.7 on 2025-11-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargoAtuante', models.CharField(max_length=100)),
                ('cargoNivel', models.CharField(max_length=50)),
                ('faixaSalarial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEmpresa', models.CharField(max_length=60)),
                ('CNPJ', models.IntegerField(unique=True)),
                ('endereco', models.CharField(max_length=100)),
                ('areaAtuacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(max_length=100)),
                ('CPF', models.IntegerField(unique=True)),
                ('dataAdmissao', models.DateTimeField(auto_now_add=True)),
                ('emailCorporativo', models.EmailField(max_length=254, unique=True)),
                ('cargo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargo')),
                ('empresa_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
